
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dell
 */
public class Splacescreen extends javax.swing.JFrame{

    /**
     * Creates new form Splacescreen
     */
    public Splacescreen(){
        initComponents();
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        progressnumber = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(251, 192, 58));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 192, 58));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\__my all of the study met__\\2nd year\\emerging\\Appliances_IS\\src\\apng_img\\giphy.gif")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        progressnumber.setText("0%");
        jPanel1.add(progressnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, -1, -1));

        jProgressBar1.setBackground(new java.awt.Color(251, 192, 58));
        jProgressBar1.setForeground(new java.awt.Color(204, 0, 0));
        jProgressBar1.setMinimumSize(new java.awt.Dimension(5, 5));
        jProgressBar1.setPreferredSize(new java.awt.Dimension(146, 5));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 511, 890, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException{
        /* Set the Nimbus look and feel */
        
        Splacescreen Splacescreen=new Splacescreen();
        Splacescreen.setVisible(true);
        AppliancesInfo AppliancesInfo=new AppliancesInfo();

        Random randomm=new Random();
        String number;
        number=Integer.toString(randomm.nextInt(3)+1);
        int no=0;
        if(number.equals("1")){
            Splacescreen.jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\__my all of the study met__\\2nd year\\emerging\\Appliances_IS\\src\\apng_img\\cameragif.gif"));
            Splacescreen.jPanel1.setBackground(new java.awt.Color(255,255,255));
            no=50;
        }
        if(number.equals("2")){
            Splacescreen.jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\__my all of the study met__\\2nd year\\emerging\\Appliances_IS\\src\\apng_img\\giphy.gif"));
            no=50;
        }
        if(number.equals("3")){
            Splacescreen.jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\__my all of the study met__\\2nd year\\emerging\\Appliances_IS\\src\\apng_img\\cameragif1.gif"));
            Splacescreen.jPanel1.setBackground(new java.awt.Color(0,0,0));
            Splacescreen.progressnumber.setForeground(new java.awt.Color(255,255,255));
            no=60;
        }
        for(int i=0;i<=100;i++){

            Thread.sleep(no);
            Splacescreen.progressnumber.setText(Integer.toString(i)+"%");
            Splacescreen.jProgressBar1.setValue(i);
            if(i==100){
                AppliancesInfo.setVisible(true);
                Splacescreen.dispose();
            }
        }
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
            for(javax.swing.UIManager.LookAndFeelInfo info:javax.swing.UIManager.getInstalledLookAndFeels()){
                if("Nimbus".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch(ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Splacescreen.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }catch(InstantiationException ex){
            java.util.logging.Logger.getLogger(Splacescreen.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }catch(IllegalAccessException ex){
            java.util.logging.Logger.getLogger(Splacescreen.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }catch(javax.swing.UnsupportedLookAndFeelException ex){
            java.util.logging.Logger.getLogger(Splacescreen.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel progressnumber;
    // End of variables declaration//GEN-END:variables
}
